### ISSUE TITLE
Feedback Request: AWS-02 Pricing

### ISSUE THREAD

**Issue by Acron0815** [TechGrounds-Cloud8/cloud8-Acron0815#29]
**Feedback Request [Pricing]**
Permalink to file: [LINK](https://github.com/TechGrounds-Cloud8/cloud8-Acron0815/blob/main/Week%204/Opdracht-2-AWS-02%20Pricing.md)

Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by benbui797** [comment]
I think you could add a little bit more info:
- Elaborate on the four advantages of the pricing model
- What does the free tier include?
- Capex vs Opex (what does it mean and what are the potentional benefits?)

Casper mentioned that AWS values their market strategy a lot and that this will come back in the exam, so I think it may be valueable to dig a little bit deeper into

**Comment by Acron0815** [comment]
Sorry, as you can see is AWS-02 Pricing "Under Construction"

**Comment by Tjomba1996** [comment]
- Nice analogy!
- Missing a bit of layout.
- Maybe use some examples for CapEx and OpEx

**Comment by abdeslamazhir** [comment]
**Summary**
- Does the summary describe the subject matter fully? yes
- Is the summary written in own words? yes
- Is there crucial information missing in the summary? no
- Is the description clear enough? yes

**Key Terminology**
- Are there missing key terms? no
- Are the key terms explained well? yes

**Sources**
- Are the sources mentioned? yes
- Are the mentioned sources correct? yes

**Excercise**
(Where applicable)
- Is the result correct? yes
- Are the experienced problems and solutions described well? yes

**Comment by Acron0815** [comment]
Thanks for the suggestion, I'll fix it as soon as possible
