### ISSUE TITLE
Feedback Request: AWS-03 Advantages of the Cloud

### ISSUE THREAD

**Issue by Acron0815** [TechGrounds-Cloud8/cloud8-Acron0815#30]
**Feedback Request [Advantages of the Cloud]**
Permalink to file: [LINK](https://github.com/TechGrounds-Cloud8/cloud8-Acron0815/blob/main/Week%204/Opdracht-3-AWS-03%20Advantages%20of%20the%20Cloud.md)

Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by abdeslamazhir** [comment]
**Summary**
- Does the summary describe the subject matter fully? yes
- Is the summary written in own words? -
- Is there crucial information missing in the summary? no
- Is the description clear enough? yes

**Key Terminology**
- Are there missing key terms? no
- Are the key terms explained well? yes, in the exercise

**Sources**
- Are the sources mentioned? yes
- Are the mentioned sources correct? yes

**Excercise**
(Where applicable)
- Is the result correct? yes
- Are the experienced problems and solutions described well? yes

**Comment by benbui797** [comment]
Looks good, all the points are mentioned and explained! I have noticed that they can use different words for the same concepts sometimes, so it might be worth keeping that in mind when we are preparing for the exam :)
