### ISSUE TITLE
Feedback Request: AWS-05 S3 Simple Storage Service (S3)

### ISSUE THREAD

**Issue by Acron0815** [TechGrounds-Cloud8/cloud8-Acron0815#32]
**Feedback Request [Simple Storage Service (S3)]**
Permalink to file: [LINK](https://github.com/TechGrounds-Cloud8/cloud8-Acron0815/blob/main/Week%204/Opdracht-5-AWS-05%20S3.md)

Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by benbui797** [comment]
Nailed the exercise! 

I was a bit confused what an object is exactly (since we just upload a file and then 'suddenly' it's an object...) No clue if it's important for the exam, but it might be something to look into when you have the time :)
