### ISSUE TITLE
Feedback Request: AWS-06 EC2 Elastic Compute Cloud (EC2)

### ISSUE THREAD

**Issue by Acron0815** [TechGrounds-Cloud8/cloud8-Acron0815#33]
**Feedback Request [Elastic Compute Cloud (EC2)]**
Permalink to file: [LINK](https://github.com/TechGrounds-Cloud8/cloud8-Acron0815/blob/main/Week%204/Opdracht-6-AWS-06%20EC2.md)

Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by benbui797** [comment]
Everything looks good! The summarisation is nice and compact and the final results are correct.

In your challenges, you write that you encountered many pitfalls, I would have liked to see what those pitfalls were and how you solved them :)

**Comment by Acron0815** [comment]
Hey Ben,
Thanks for the comment, I'll try to describe the pitfalls later tonight!
