### ISSUE TITLE
Feedback Request: AWS-07 EBS

### ISSUE THREAD

**Issue by Acron0815** [TechGrounds-Cloud8/cloud8-Acron0815#34]
**Feedback Request [AWS-07 EBS]**
Permalink to file: [LINK](https://github.com/TechGrounds-Cloud8/cloud8-Acron0815/blob/main/Week%204/Opdracht-7-AWS-07%20EBS.md)

Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by benbui797** [comment]
I think the first sentence should remove the "not". EBS is best suited for when you frequently access and modify the data that is stored on it. If it's not frequent (such as an archive), then S3 is better suited.

The first part of the exercise is correct, but I'm missing the final part where you create a new volume from the snapshot, remove the textfile from the original volume and mount the new one it to the VM.  Have all screenshots been included correctly?

**Comment by Acron0815** [comment]
Thanks Ben for your comment, I'll check and improve it later today!
