### ISSUE TITLE
Feedback Request: Opdracht-2-AWS-10 VPC

### ISSUE THREAD

**Issue by Acron0815** [TechGrounds-Cloud8/cloud8-Acron0815#37]
**Feedback Request [Opdracht-2-AWS-10 VPC]**
Permalink to file: [LINK](https://github.com/TechGrounds-Cloud8/cloud8-Acron0815/blob/main/Week%205/Opdracht-2-AWS-10%20VPC.md)

Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by yismailmo** [comment]
Looks good and in Key terminology i missed the explanation of the private cloud because you were comparing virtual private cloud and private cloud, however you explained very well the virtual private cloud.
