### ISSUE TITLE
Feedback Request: Opdracht 2: GIT-02 Markdown

### ISSUE THREAD

**Issue by Acron0815** [TechGrounds-Cloud8/cloud8-Acron0815#4]
**Feedback RequestOpdracht 2: GIT-02 Markdown**
Permalink to file: [GIT-02 Markdown]https://github.com/TechGrounds-Cloud8/cloud8-Acron0815/blob/main/00_includes/BoxKat.PNG

Markdown turns common “plaintext” formatting conventions like asterisks, indentation, and so on into HTML markup. If you need anything more complicated (say, an image with a caption or a link that opens in a new window), you need to mix markdown and raw HTML. Markdown is easy to remember for simple stuff (blockquotes, italics, headings, etc) but more complicated structures require extensions to the standard that are just as tweaky as HTML.

**Sources**
- https://www.markdownguide.org/
- https://www.tremplin-numerique.org/de/Was-ist-Markdown-und-wie-wird-es-verwendet%3F
- https://toptips.fr/quest-ce-que-markdown-et-comment-lutilisez-vous/

Share the link to this issue with your peers.

**Comment by se0727** [comment]
idem dito als comment on issue 1

**Comment by Acron0815** [comment]
Hallo Sanjai,
Bedankt voor de suggesties, ik zal vanavond/nacht nog proberen de fouten te herstellen!
Tot straks,
André
