### ISSUE TITLE
Feedback Request: Opdracht 4: LNX-02 Files and directories

### ISSUE THREAD

**Issue by Acron0815** [TechGrounds-Cloud8/cloud8-Acron0815#6]
**Feedback Request Opdracht 4: LNX-02 Files and directories**
Permalink to file: [LNX-02 Files and directories]https://github.com/TechGrounds-Cloud8/cloud8-Acron0815/tree/main/00_includes/LNX-02%20Files%20and%20directories

Template for peers for review: 
```
**Sources**
https://linuxize.com/post/how-to-create-users-in-linux-using-the-useradd-command/ https://linuxize.com/post/how-to-add-user-to-sudoers-in-ubuntu/

**Excercise**
Create a new user in your VM. useradd The new user should be part of an admin group. ?? The new user should have a password. The new user should be able to use ‘sudo
```

Share the link to this issue with your peers.

**Comment by se0727** [comment]
idem dito, onduidelijk welke mappen etc

**Comment by Acron0815** [comment]
Hallo Sanjai,
Bedankt voor de suggesties, ik zal vanavond/nacht nog proberen de fouten te herstellen!
Tot straks,
André
