### ISSUE TITLE
Feedback Request: Opdracht 5: LNX-03 Working with text (CLI)

### ISSUE THREAD

**Issue by Acron0815** [TechGrounds-Cloud8/cloud8-Acron0815#7]
**Feedback Request Opdracht 5: LNX-03 Working with text (CLI)**
Permalink to file: [LNX-03 Working with text (CLI)]https://github.com/TechGrounds-Cloud8/cloud8-Acron0815/tree/main/00_includes/LNX-03%20Working%20with%20text%20(CLI)

Template for peers for review: 
```
It practices in creating an input folder, and output, creating and reading text.

**Key Terminology**
[Write a list of key terminology with a short description. To prevent duplication you can reference to previous excersizes.]

**Sources**
- Google.com

Share the link to this issue with your peers.

**Comment by se0727** [comment]
idem dito

**Comment by Acron0815** [comment]
Hallo Sanjai,
Bedankt voor de suggesties, ik zal vanavond nog proberen de fouten te
herstellen!
Tot straks,
André

Op zo 8 mei 2022 22:11 schreef Sanjai ***@***.***>:
