### ISSUE TITLE
Feedback Request: Opdracht 7: LNX-05 File permissions

### ISSUE THREAD

**Issue by Acron0815** [TechGrounds-Cloud8/cloud8-Acron0815#9]
**Feedback Request [Opdracht 7: LNX-05 File permissions]**
Permalink to file: [LNX-05 File permissions]https://github.com/TechGrounds-Cloud8/cloud8-Acron0815/blob/main/00_includes/LNX-05%20File%20permissions/File%20permissions.PNG

Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by se0727** [comment]
idem dito, geen uitwerking alleen een screenshot

**Comment by Acron0815** [comment]
Hallo Sanjai,
Bedankt voor de suggesties, ik zal vanavond/nacht nog proberen de fouten te herstellen!
Tot straks,
André
